#H2-console
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:db;MODE=MYSQL;
#spring.datasource.username=sa
#spring.datasource.password=

spring:
  datasource:
    url: ENC(hcf8qwjeIBxdjauNqEipd3dQBzzQtilhNe1R1XKdBLNgzDVXAjcbD1Iusfy1w7eHUdEXEKYY3HEieJU7Lt0csdQpSG3AZ5Hlsx86AOzFig8dQK/he8zoRLDZo4UdWVUeV9pIFhuHnic=)
    username: mini
    password: ENC(K24TxxKZXRl29EF9x4c9crzGlMox9loh)
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=

secret:
  key: ${{ secrets.AWS_JASYPT_KEY }}